name: Build UI

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    -  name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd ui && docker build -f Dockerfile -t rooysv/karma-ui:${{ steps.get_version.outputs.VERSION }} .
    - name: Push the Docker image
      run: cd ui && rooysv/karma-ui:${{ steps.get_version.outputs.VERSION }}
